name: Content Linter

on:
  push:
    paths:
      - "_posts/**/*.markdown"
  pull_request:
    paths:
      - "_posts/**/*.markdown"

jobs:
  content-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          keywords-file: .github/scripts/keywords.txt
          posts-dir: _posts
